export const findByTypeAndLevel = (type: any, level: any) => {
  return staticData.find((item) => item.type === type && item.level === level) || null;
};

export const staticData = [
  {
    cost: 0,
    imageUrl: '/racer-car-elements/car-0.png',
    specialEffects: 'Everyone first car',
    name: 'Basic Car',
    type: 'car',
    level: 0,
  },
  {
    cost: 100,
    imageUrl: '/racer-car-elements/car-1.png',
    specialEffects: 'Speed Surge 10%',
    name: 'FORD',
    type: 'car',
    level: 1,
  },
  {
    cost: 250,
    imageUrl: '/racer-car-elements/car-2.png',
    specialEffects: 'Earn score 10% faster',
    name: 'Truck',
    type: 'car',
    level: 2,
  },
  {
    cost: 500,
    imageUrl: '/racer-car-elements/car-3.png',
    specialEffects: 'When hit 30% survival',
    name: 'Honda 🐂',
    type: 'car',
    level: 3,
  },
  {
    cost: 1000,
    imageUrl: '/racer-car-elements/car-4.png',
    specialEffects: 'Earn extra 500 per game',
    name: 'Maybach',
    type: 'car',
    level: 4,
  },
  {
    cost: 2000,
    imageUrl: '/racer-car-elements/car-5.png',
    specialEffects: 'Have 1 more life, 50% bigger',
    name: 'Stretch Lincoln',
    type: 'car',
    level: 5,
  },
  {
    cost: 3000,
    imageUrl: '/racer-car-elements/car-6.png',
    specialEffects: 'Earn 30% faster',
    name: 'Bugatti',
    type: 'car',
    level: 6,
  },
  {
    cost: 4000,
    imageUrl: '/racer-car-elements/car-7.png',
    specialEffects: 'Earn 45% faster',
    name: 'Pagani',
    type: 'car',
    level: 7,
  },
  {
    cost: 100000,
    imageUrl: '/racer-car-elements/car-8.png',
    specialEffects: 'Legendary Effect, Earning * 2',
    name: 'Nascar',
    type: 'car',
    level: 8,
  },
  {
    cost: 1000,
    imageUrl: '/racer-car-elements/equipment-0.png',
    specialEffects: 'Left and right faster by 30%',
    name: 'Golden Alloy',
    type: 'wheels',
    level: 0,
  },
  {
    cost: 2000,
    imageUrl: '/racer-car-elements/equipment-1.png',
    specialEffects: 'Left and right faster by 50%',
    name: 'Carbon Fiber',
    type: 'wheels',
    level: 1,
  },
  {
    cost: 4000,
    imageUrl: '/racer-car-elements/equipment-2.png',
    specialEffects: 'Left and right faster by 70%',
    name: 'Turbo Boost',
    type: 'wheels',
    level: 2,
  },
  {
    cost: 1000,
    imageUrl: '/racer-car-elements/fuel-0.png',
    specialEffects: 'Fuel is 10% more',
    name: 'Red fuel',
    type: 'gas',
    level: 0,
  },
  {
    cost: 2000,
    imageUrl: '/racer-car-elements/fuel-1.png',
    specialEffects: 'Fuel burn rate is 15% slower',
    name: 'Nitro Fuel',
    type: 'gas',
    level: 1,
  },
  {
    cost: 4000,
    imageUrl: '/racer-car-elements/fuel-2.png',
    specialEffects: 'Fuel burn rate is down 50% in game',
    name: 'Eco Fuel',
    type: 'gas',
    level: 2,
  },
];
